server:
  port: 9990

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Development/microservices/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
